import 'dart:convert';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../services/firebase_service.dart';
import '../../services/gemini_service.dart';
import '../../models/incident_model.dart';
import '../auth/auth_provider.dart';

// ── Models ───────────────────────────────────────────────────────────────────

enum ActivationPhase { idle, analyzing, confirmed, error }

class PlaybookStep {
  final int step;
  final String action;
  final String owner;
  final String timeframe;

  const PlaybookStep({
    required this.step,
    required this.action,
    required this.owner,
    this.timeframe = '',
  });

  factory PlaybookStep.fromJson(Map<String, dynamic> json) {
    return PlaybookStep(
      step: json['step'] as int? ?? 0,
      action: json['action'] as String? ?? '',
      owner: json['owner'] as String? ?? '',
      timeframe: json['timeframe'] as String? ?? '',
    );
  }
}

class ActivationState {
  final ActivationPhase phase;
  final String incidentType;
  final String location;
  final String description;
  final String severity;
  final String incidentId;
  final List<PlaybookStep> playbook;
  final String? errorMessage;

  const ActivationState({
    this.phase = ActivationPhase.idle,
    this.incidentType = '',
    this.location = '',
    this.description = '',
    this.severity = '',
    this.incidentId = '',
    this.playbook = const [],
    this.errorMessage,
  });

  ActivationState copyWith({
    ActivationPhase? phase,
    String? incidentType,
    String? location,
    String? description,
    String? severity,
    String? incidentId,
    List<PlaybookStep>? playbook,
    String? errorMessage,
  }) =>
      ActivationState(
        phase: phase ?? this.phase,
        incidentType: incidentType ?? this.incidentType,
        location: location ?? this.location,
        description: description ?? this.description,
        severity: severity ?? this.severity,
        incidentId: incidentId ?? this.incidentId,
        playbook: playbook ?? this.playbook,
        errorMessage: errorMessage ?? this.errorMessage,
      );
}

// ── Notifier ──────────────────────────────────────────────────────────────────

class ActivationNotifier extends StateNotifier<ActivationState> {
  final FirebaseService _firebaseService;
  final GeminiService _geminiService;
  final Ref _ref;

  ActivationNotifier(this._firebaseService, this._geminiService, this._ref)
      : super(const ActivationState());

  void setType(String type) => state = state.copyWith(incidentType: type);
  void setLocation(String loc) => state = state.copyWith(location: loc);
  void setDescription(String desc) => state = state.copyWith(description: desc);

  Future<void> analyzeAndActivate() async {
    if (state.phase == ActivationPhase.analyzing) return;
    state = state.copyWith(phase: ActivationPhase.analyzing);
    
    try {
      // 1. Classify with Gemini
      final classificationStr = await _geminiService.classifyIncident(state.description);
      Map<String, dynamic> classData = {};
      try {
        // Strip markdown blocks if any
        final cleanStr = classificationStr.replaceAll('```json', '').replaceAll('```', '').trim();
        classData = jsonDecode(cleanStr);
      } catch (e) {
        // Fallback
        classData = {
          'type': state.incidentType.isNotEmpty ? state.incidentType : 'Other',
          'severity': 'SEV-3'
        };
      }

      final type = classData['type'] as String? ?? state.incidentType;
      final severityStr = classData['severity'] as String? ?? 'SEV-3';
      
      // Parse severity string to int (SEV-1 = 1, etc.)
      int sevInt = 3;
      if (severityStr.contains('1')) sevInt = 1;
      if (severityStr.contains('2')) sevInt = 2;
      if (severityStr.contains('4')) sevInt = 4;
      if (severityStr.contains('5')) sevInt = 5;

      // 2. Generate playbook
      final playbookStr = await _geminiService.generatePlaybook(type, severityStr);
      List<PlaybookStep> playbook = [];
      try {
        final cleanPb = playbookStr.replaceAll('```json', '').replaceAll('```', '').trim();
        final List<dynamic> pbList = jsonDecode(cleanPb);
        playbook = pbList.map((e) => PlaybookStep.fromJson(e)).toList();
      } catch (e) {
        playbook = [
          const PlaybookStep(step: 1, action: 'Assess the situation', owner: 'Manager')
        ];
      }

      // 3. Create incident in Firestore
      final authState = _ref.read(authProvider);
      final reportedBy = authState.user?.uid ?? 'unknown';

      final incident = IncidentModel(
        id: '', // Generated by Firestore
        type: type,
        location: state.location,
        severity: sevInt,
        status: 'active',
        reportedBy: reportedBy,
        timestamp: DateTime.now(),
        notes: state.description,
        description: state.description,
      );

      final incidentId = await _firebaseService.createIncident(incident);

      // 4. Update state
      state = state.copyWith(
        phase: ActivationPhase.confirmed,
        incidentType: type,
        severity: severityStr,
        incidentId: incidentId,
        playbook: playbook,
      );
      
    } catch (e) {
      state = state.copyWith(
        phase: ActivationPhase.error,
        errorMessage: 'Failed to activate crisis: $e',
      );
    }
  }

  void reset() => state = const ActivationState();
}

final activationProvider = StateNotifierProvider<ActivationNotifier, ActivationState>((ref) {
  final fbService = ref.watch(firebaseProvider);
  final geminiService = ref.watch(geminiProvider);
  return ActivationNotifier(fbService, geminiService, ref);
});
